config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :businesses do
    resources :reviews
  end
  resources :users, only: [:new, :create] do
    resources :bizlists do
      get 'add', to: 'bizlists#add'
      get 'remove', to: 'bizlists#remove'
    end
  end
  resources :bizlists
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/biz_search', to: 'bizlists#search'
  get '/biz_favs', to: 'bizlists#favs'
  get '/biz_most_ratings', to: 'businesses#most_ratings'
  get '/biz_filter_within_last_24_hours', to: 'bizlists#last_day'
  get '/remove_bizlist', to: 'bizlists#list_destroy'
  get '/add_biz_as_favorite', to: 'businesses#fav'
  get '/auth/google/callback', to: 'users#google_login'
  get '*path', to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bizlist.rb
class Bizlist < ApplicationRecord

  belongs_to :user
  has_many :bizlist_businesses
  has_many :businesses, through: :bizlist_businesses

  validates :name, presence: true

  def add_to
  end

  def remove_from
  end

  def self.verify_presence(bizlist, param)
    !!Business.find_by(id: param) && !bizlist.businesses.find_by(id: param)
  end

  def remove_biz(bizlist, param)
    join = bizlist.bizlist_businesses.find_by(business_id: param)
    join.delete
  end

  def delete_bizlist(bizlist)
    bizlist.bizlist_businesses.each {|x| x.delete} unless bizlist.bizlist_businesses.empty?
    bizlist.destroy
  end

end

app/controllers/bizlists_controller.rb
class BizlistsController < ApplicationController
  before_action :require_login
  before_action :init_user
  before_action :init_username
  before_action :init_user_bizlist, only: [:show, :edit, :update, :destroy]

  def index
    @bizlists = current_user.bizlists
    @businesses = Business.all
  end

  def new
    @bizlist = Bizlist.new
  end

  def add
    @bizlist = Bizlist.find_by(id: params[:bizlist_id])
  end

  def remove
    @bizlist = Bizlist.find_by(id: params[:bizlist_id])
    if !@bizlist.businesses.any?
      redirect_to bizlist_path(@bizlist)
      flash[:biz_not_present] = "No biz to remove from this bizlist"
    end
  end

  def create
    @bizlist = @user.bizlists.build(bizlist_params)
    if @bizlist.save
      flash[:message] = "Bizlist Successfully Created"
      redirect_to user_bizlists_path(current_user)
    else
      flash[:name_required] = "Bizlist name required"
      redirect_to new_user_bizlist_path(current_user)
    end
  end

  def update
    if Bizlist.verify_presence(@bizlist, params[:bizlist]['add_to'])
         @bizlist.businesses << Business.find_by(id: params[:bizlist]['add_to'])
         redirect_to bizlist_path(@bizlist)
         flash[:biz_added] = "Biz successfully added to this bizlist"
    elsif !!@bizlist.businesses.find_by(id: params[:bizlist]['add_to'])
         redirect_to bizlist_path(@bizlist)
         flash[:biz_present] = "Biz already added to this bizlist"
    elsif !!params[:bizlist]['remove_from']
         @bizlist.remove_biz(@bizlist, params[:bizlist]['remove_from'])
         redirect_to bizlist_path(@bizlist)
         flash[:biz_removed] = "Biz removed from this bizlist"
    else
         @bizlist.update(bizlist_params)
           if @bizlist.save
             redirect_to bizlist_path(@bizlist)
             flash[:biz_updated] = "Bizlist updated"
           else
             flash[:name_required] = "Bizlist name required"
             redirect_to edit_user_bizlist_path(current_user, @bizlist)
           end
    end
 end

 def favs
   @bizlists = current_user.bizlists
   @businesses = Business.user_favs(current_user.id)
   if @businesses.empty?
     flash[:no_fav_search_results] = "No businesses marked as favorite"
   else
     flash[:fav_biz] = "Business favorites"
   end
   render :index
 end

 def search
    @bizlists = current_user.bizlists
    @businesses = Business.search(params[:query])
    if @businesses.empty?
      flash[:no_search_results] = "No business found"
    end
    render :index
 end

 def last_day
   @bizlists = current_user.bizlists
   @businesses = Business.last_day
   if @businesses.empty?
     flash[:no_search_results] = "No business found"
   end
   render :index
 end

 def list_destroy
   @bizlist = Bizlist.find_by(id: params[:bizlist])
    if !!@bizlist
      @bizlist.delete_bizlist(@bizlist)
      redirect_to user_bizlists_path(current_user)
      flash[:biz_delete] = "Bizlist deleted"
    else
      render :show
      flash[:biz_error] = "This bizlist could not be deleted"
    end
  end

  private

  def init_user
    @user = User.find_by(id: params[:user_id])
  end

  def init_username
    @username = current_user.username
  end

  def bizlist_params
    params.require(:bizlist).permit(:name, :description, :user_id)
  end

  def init_user_bizlist
    @bizlist = Bizlist.find_by(id: params[:id])
    unless !!@bizlist && (@bizlist.user_id == current_user.id)
      redirect_to bizlists_path
    end
  end
end

app/helpers/bizlists_helper.rb
module BizlistsHelper
end

app/views/bizlists/_add.html.erb
<div class="test test_2">
  <h2 class="text_alignment text_alignment_2">Add Biz to Bizlist</h2><span id="vert"></span>
    <%= form_for [user, bizlist] do |f| %>
    <%= f.collection_select :add_to, Business.all, :id, :name %>
      <%= f.submit %>
    <% end %>
</div>

app/views/bizlists/_form.html.erb
<% if flash[:name_required] %>
  <div class="alert_align2">
    <h2><%= flash[:name_required] %></h2>
  <hr class="hr_color">
  </div>
<% end %>

<div class="test test_2">
  <h2 class="text_alignment"><%= "#{params[:action].titleize}" %> Bizlist</h2><span id="vert"></span>
    <%= form_for [user, bizlist] do |f| %>
      <h3><%= f.label :name %></h3> <%= f.text_field :name %>
      <h3><%= f.label :description %></h3> <%= f.text_area :description, :cols => 20, :rows => 5 %><br><br>
      <%= f.submit %>
    <% end %>
</div>

app/views/bizlists/_remove.html.erb
<div class="test test_2">
  <h2 class="text_alignment text_alignment_2">Remove Biz from Bizlist</h2><span id="vert"></span>
  <%= form_for [user, bizlist] do |f| %>
  <%= f.collection_select :remove_from, bizlist.businesses, :id, :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bizlists/add.html.erb
<%= render 'common/user_nav' %>

<%= render partial: "add", locals: {user: @user, bizlist: @bizlist} %>

app/views/bizlists/edit.html.erb
<%= render 'common/user_nav' %>

<%= render partial: "form", locals: {user: @user, bizlist: @bizlist} %>

app/views/bizlists/index.html.erb
<%= render 'common/user_nav' %>


<div class="row">
  <div class="col sidebar">
  <% if @bizlists.count == 0 %>
    <div class="flex_header">
      My Bizlists
    </div>
      <hr class="hr_style">
      <br>
      <% if flash[:biz_delete] %>
        <div class="alert_align4">
          <h2><%= flash[:biz_delete] %></h2>
          <br>
          <hr class="hr_color"><br>
        </div>
      <% end %>
    <div>
      Select Create Bizlist from the menu to make a new list for biz monitoring / organizing.
    </div>
  <% else %>
  <div class="flex_header">
    My Bizlists
  </div>
  <hr class="hr_style">
    <br>
  <% if flash[:message] || flash[:biz_delete] || flash[:warning] %>
    <div class="alert_align4">
      <h2><%= flash[:message] || flash[:biz_delete] || flash[:warning] %></h2>
      <br>
      <hr class="hr_color">
    </div>
  <% end %>
    <% @bizlists.reverse.each do |bizlist| %>
          <h2><%= link_to bizlist.name, user_bizlist_path(current_user, bizlist) %></h2>
          <div>
            <% if !bizlist.description.empty? %>
               <hr><br>Description:&nbsp<%= bizlist.description %><br><br>
            <% end %>
          </div><hr class="hr_color">
    <% end %>
  <% end %>
  </div>

  <div class="col mainbar">
    <% if @businesses.count == 0 %>
      <div class="flex_header">
        Biz Index
      </div>
        <hr class="hr_style">
        <br>
        <% if flash[:no_search_results] || flash[:logged_in_with_google] || flash[:no_fav_search_results] %>
          <div class="alert_align4">
            <h2><%= flash[:no_search_results] || flash[:logged_in_with_google] || flash[:no_fav_search_results] %></h2>
            <br>
            <hr class="hr_color"><br>
          </div>
        <% end %>
      <div>
        Select Add a Business from the menu to add a new business.
      </div>
    <% else %>
    <div class="search_align">
      <%= form_tag("/biz_search", method: "get") do %>
      <%= text_field_tag :query, "Search by Business" %>
      <%= submit_tag "Search" %>&nbsp&nbsp|&nbsp&nbsp<hr>
      <% end %>
    </div>

    <div class="search_align search_align_1">
      <%= button_to "Biz reviewed within last 24 hours", biz_filter_within_last_24_hours_path, method: :get %><hr>
    </div>

    <div class="search_align search_align_3">
      &nbsp&nbsp|&nbsp&nbsp<hr>
    </div>

    <div class="search_align search_align_2">
      <%= button_to "Biz with most reviews", biz_most_ratings_path, method: :get %><hr>
    </div>

    <div class="flex_header">
      Biz Index
    </div>
    <hr class="hr_style">
      <br>
    <% if flash[:business] || flash[:logged_in_with_google] || flash[:fav_biz] %>
      <div class="alert_align4">
        <h2><%= flash[:business] || flash[:logged_in_with_google] || flash[:fav_biz] %></h2>
        <br>
        <hr class="hr_color">
      </div>
    <% end %>
      <% @businesses.reverse.each do |business| %>
            <h2><%= link_to business.name, business_path(business) %></h2>
              <% if business.reviews.empty? %>
                <div>no reviews</div><br><hr><br>
              <% else%>
              <div>last reviewed <%= time_ago_in_words(business.reviews.search.created_at) %> ago</div><br><hr><br>
                <div>average rating:&nbsp<div class="Stars" style="--rating: <%= business.overall_rating %>;"></div></div><br><hr><br>
              <% end %>
            <div>
              <% if !business.description.empty? %>
                 Description:&nbsp<%= business.description %><br><br>
              <% end %>
            </div>
            <div>Address:&nbsp<%= business.address %></div>
            <br><hr class="hr_color">
      <% end %>
    <% end %>
    </div>

app/views/bizlists/new.html.erb
<%= render 'common/user_nav' %>

<%= render partial: "form", locals: {user: @user, bizlist: @bizlist} %>

app/views/bizlists/remove.html.erb
<%= render 'common/user_nav' %>

<%= render partial: "remove", locals: {user: @user, bizlist: @bizlist} %>

app/views/bizlists/show.html.erb
<%= render 'common/user_nav' %>

<div class="biz_align">
  <%= render 'common/bizlist_show_menu' %>
</div>

   <div class="row">
     <div class="col sidebar">
       <div class="flex_header">
         Bizlist
       </div>
         <hr class="hr_style">
         <br>
         <% if flash[:biz_updated] %>
           <div class="alert_align4">
             <h2><%= flash[:biz_updated] %></h2>
             <br>
             <hr class="hr_color">
           </div>
         <% end %>
           <div>
             <h2><%= @bizlist.name %></h2>
           </div><hr><br>
           <div>
             <% if !@bizlist.description.empty? %>
               Description:&nbsp<%= @bizlist.description %>
             <% end %>
           </div>
     </div>

     <div class="col mainbar">
         <div class="flex_header">
           Biz added to this bizlist
         </div>
           <hr class="hr_style">
           <br>
           <% if flash[:biz_added] || flash[:biz_present] || flash[:biz_removed] || flash[:biz_not_present] %>
             <div class="alert_align4">
               <h2><%= flash[:biz_added] || flash[:biz_present] || flash[:biz_removed] || flash[:biz_not_present] %></h2>
               <br>
               <hr class="hr_color">
             </div>
           <% end %>
         <div>
           <% if @bizlist.businesses.count == 0 %>
              <br>No businesses have been added to this bizlist.
           <% else %>
               <% @bizlist.businesses.reverse.each do |business| %>
                     <div><h2><%= link_to business.name, business_path(business) %></h2></div><hr><br>
                     <% if business.reviews.empty? %>
                       <div>no reviews</div><br><hr><br>
                     <% else %>
                       <div>average rating:&nbsp<div class="Stars" style="--rating: <%= business.overall_rating %>;"></div></div><br><hr><br>
                     <% end %>
                     <% if !business.description.empty? %>
                       <div>Description:&nbsp<%= business.description %></div><br>
                     <% end %>
                     <div>Address:&nbsp<%= business.address %></div><br><hr class="hr_color">
               <% end %>
           <% end %>
         </div>
       </div>