config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :businesses do
    resources :reviews
  end
  resources :users, only: [:new, :create] do
    resources :bizlists do
      get 'add', to: 'bizlists#add'
      get 'remove', to: 'bizlists#remove'
    end
  end
  resources :bizlists
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/biz_search', to: 'bizlists#search'
  get '/biz_favs', to: 'bizlists#favs'
  get '/biz_most_ratings', to: 'businesses#most_ratings'
  get '/biz_filter_within_last_24_hours', to: 'bizlists#last_day'
  get '/remove_bizlist', to: 'bizlists#list_destroy'
  get '/add_biz_as_favorite', to: 'businesses#fav'
  get '/auth/google/callback', to: 'users#google_login'
  get '*path', to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/_bizlist_show_menu.html.erb
<div class="add-button">
  <div class="sub-button tl"></div>
  <div><%= link_to "add", user_bizlist_add_path(current_user, @bizlist), :method => "get", class: "sub-button tl" %></div>
  <div><%= link_to "edit list", edit_user_bizlist_path(current_user, @bizlist), :method => "get", class: "sub-button bl" %></div>
  <div><%= link_to "remove biz", user_bizlist_remove_path(current_user, @bizlist), :method => "get", class: "sub-button br" %></div>
  <div><%= link_to "delete list", remove_bizlist_path(:bizlist => @bizlist), class: "sub-button tr" %></div>
</div>

app/views/common/_business_show_menu.html.erb
<div class="add-button">
  <div class="sub-button tl"></div>
  <div><%= link_to "review", new_business_review_path(@business), :method => "get", class: "sub-button tl" %></div>
  <div><%= link_to "fav?", add_biz_as_favorite_path(@business), :method => "get", class: "sub-button tr" %></div>
  <div><%= link_to "edit biz", edit_business_path(@business), :method => "get", class: "sub-button bl" %></div>
  <div><%= link_to "index", user_bizlists_path(current_user), :method => "get", class: "sub-button br" %></div>
</div>

app/views/common/_show_menu.html.erb
<div class="add-button">
  <div class="sub-button tl"></div>
  <div><%= link_to "add", user_bizlists_path(current_user), :method => "get", class: "sub-button tl" %></div>
  <div><%= link_to "delete", user_bizlists_path(current_user), :method => "get", class: "sub-button tr" %></div>
  <div><%= link_to "edit", user_bizlists_path(current_user), :method => "get", class: "sub-button bl" %></div>
  <div><%= link_to "index", user_bizlists_path(current_user), :method => "get", class: "sub-button br" %></div>
</div>

app/views/common/_sign_in_nav.html.erb
<!DOCTYPE html>

<html>
  <head>

      <title>bizrev</title>

      <%= stylesheet_link_tag 'application' %>

  </head>

  <body>

    <nav role="navigation">

      <div id="menuToggle">

        <input type="checkbox" />

          <span></span>
          <span></span>
          <span></span>

        <ul id="menu">
          <li><%= link_to "Home »", root_path, :method => "get" %></li>
          <a href="#"><li>About »</li></a>
          <a href="#"><li>Info »</li></a>
          <li><%= link_to "Logout »", logout_path, :method => "get" %> </li>
        </ul>
      </div>
    </nav>

    <%= content_tag(:span, 'Menu', class: "rel") %>

    <%= yield %>

  </body>

</html>

app/views/common/_user_nav.html.erb
<!DOCTYPE html>

<html>
  <head>
      <title>bizrev</title>
      <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <nav role="navigation">
      <div id="menuToggle">
        <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
        <ul id="menu">
          <% if logged_in? %>
            <li><%= link_to "Biz Index", user_bizlists_path(current_user), :method => "get" %></li>
            <li><%= link_to "Create Bizlist", new_user_bizlist_path(current_user), :method => "get"%></li>
            <li><%= link_to "Add a Biz", new_business_path, :method => "get" %></li>
            <li><%= link_to "Biz Favs", biz_favs_path, method: :get %></li>
            <li><%= link_to "Logout", logout_path, :method => "get" %></li>
          <% else %>
            <li><%= link_to "Back", root_path, :method => "get" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= content_tag(:span, 'Menu', class: "rel") %>

    <% if !!@user && @user.errors.any? %>
      <div class="alert_align2">
        <% @user.errors.full_messages.reverse.each do |message| %>
        <h2><%= message %></h2>
      <% end %>
      <hr class="hr_color">
      </div>
    <% elsif flash[:login_error] %>
      <div class="alert_align2">
        <h2><%= flash[:login_error] %></h2>
      <hr class="hr_color">
      </div>
    <% end %>
      <span class="rel_nav_right">Welcome <%= @username %><hr class="hr_color"></span>
      <%= yield %>
  </body>
</html>