config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :businesses do
    resources :reviews
  end
  resources :users, only: [:new, :create] do
    resources :bizlists do
      get 'add', to: 'bizlists#add'
      get 'remove', to: 'bizlists#remove'
    end
  end
  resources :bizlists
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/biz_search', to: 'bizlists#search'
  get '/biz_favs', to: 'bizlists#favs'
  get '/biz_most_ratings', to: 'businesses#most_ratings'
  get '/biz_filter_within_last_24_hours', to: 'bizlists#last_day'
  get '/remove_bizlist', to: 'bizlists#list_destroy'
  get '/add_biz_as_favorite', to: 'businesses#fav'
  get '/auth/google/callback', to: 'users#google_login'
  get '*path', to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>bizrev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>

<html>

  <head>
      <title>bizrev</title>
      <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <nav role="navigation">
      <div id="menuToggle">
        <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
        <ul id="menu">
          <li><%= link_to "Sign up", new_user_path, :method => "get" %></li>
          <li><%= link_to "Login", login_path, :method => "get" %></li>
        </ul>
      </div>
    </nav>
      <%= content_tag(:span, 'Menu', class: "rel") %>
      <%= yield %>
  </body>
</html>